-- Add calling hours fields to Campaigns table
ALTER TABLE "Campaigns" 
ADD COLUMN IF NOT EXISTS "EnforceCallingHours" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "StartHour" INTEGER NOT NULL DEFAULT 9,
ADD COLUMN IF NOT EXISTS "EndHour" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS "IncludeWeekends" BOOLEAN NOT NULL DEFAULT false;