databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "15"
name: t4h-canvas
region: nyc
services:
- dockerfile_path: deployment/Dockerfile
  envs:
  - key: ASPNETCORE_ENVIRONMENT
    scope: RUN_TIME
    value: Production
  - key: ASPNETCORE_URLS
    scope: RUN_TIME
    value: http://+:8080
  - key: ConnectionStrings__DefaultConnection
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: JwtSettings__Secret
    scope: RUN_TIME
    value: mcgqRD2zQcxJzKHPy58zvZlKlVsmRPUFbr+REjI43dI=
  - key: JwtSettings__Issuer
    scope: RUN_TIME
    value: https://t4h-canvas-2uwxt.ondigitalocean.app
  - key: JwtSettings__Audience
    scope: RUN_TIME
    value: https://t4h-canvas-2uwxt.ondigitalocean.app
  - key: JwtSettings__ExpirationMinutes
    scope: RUN_TIME
    value: "480"
  git:
    branch: main
    repo_clone_url: https://github.com/maqboolp/CanvassingApp.git
  health_check:
    http_path: /api/health
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: api
  routes:
  - path: /api
  source_dir: /
static_sites:
- build_command: npm ci && npm run build
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: https://t4h-canvas-2uwxt.ondigitalocean.app
  github:
    branch: main
    deploy_on_push: true
    repo: maqboolp/CanvassingApp
  name: frontend
  output_dir: build
  source_dir: /frontend
EOF < /dev/null