-- Seed Default Admin Accounts
-- This script creates the default SuperAdmin and Admin accounts with working passwords
-- Default passwords that MUST be changed on first login:
-- SuperAdmin: SuperAdmin123!
-- Admin: Admin123!

-- First, delete any existing default accounts
DELETE FROM "AspNetUsers" WHERE "Email" IN ('superadmin@campaign.com', 'admin@campaign.com');

-- Create SuperAdmin account
-- Password: SuperAdmin123!
INSERT INTO "AspNetUsers" (
    "Id", 
    "UserName", 
    "NormalizedUserName", 
    "Email", 
    "NormalizedEmail",
    "EmailConfirmed", 
    "PasswordHash",
    "SecurityStamp", 
    "ConcurrencyStamp",
    "PhoneNumberConfirmed", 
    "TwoFactorEnabled", 
    "LockoutEnabled", 
    "AccessFailedCount",
    "FirstName", 
    "LastName", 
    "Role", 
    "IsActive", 
    "CreatedAt", 
    "ForcePasswordChange",
    "PhoneNumber"
) VALUES (
    gen_random_uuid()::text,
    'superadmin@campaign.com',
    'SUPERADMIN@CAMPAIGN.COM',
    'superadmin@campaign.com',
    'SUPERADMIN@CAMPAIGN.COM',
    true,
    -- This hash is for 'SuperAdmin123!' - generated by ASP.NET Core Identity
    'AQAAAAIAAYagAAAAEH3dKzJfD5X3HpYkMLbcXCrgVn7qMkJvVLhGGFqJdMGWaOyVpNqKqe5Y3qFhX5XoVg==',
    upper(replace(gen_random_uuid()::text, '-', '')),
    gen_random_uuid()::text,
    false,
    false,
    true,
    0,
    'Super',
    'Admin',
    'SuperAdmin',
    true,
    CURRENT_TIMESTAMP,
    true,  -- Force password change on first login
    NULL
);

-- Create Admin account
-- Password: Admin123!
INSERT INTO "AspNetUsers" (
    "Id", 
    "UserName", 
    "NormalizedUserName", 
    "Email", 
    "NormalizedEmail",
    "EmailConfirmed", 
    "PasswordHash",
    "SecurityStamp", 
    "ConcurrencyStamp",
    "PhoneNumberConfirmed", 
    "TwoFactorEnabled", 
    "LockoutEnabled", 
    "AccessFailedCount",
    "FirstName", 
    "LastName", 
    "Role", 
    "IsActive", 
    "CreatedAt", 
    "ForcePasswordChange",
    "PhoneNumber"
) VALUES (
    gen_random_uuid()::text,
    'admin@campaign.com',
    'ADMIN@CAMPAIGN.COM',
    'admin@campaign.com',
    'ADMIN@CAMPAIGN.COM',
    true,
    -- This hash is for 'Admin123!' - generated by ASP.NET Core Identity
    'AQAAAAIAAYagAAAAEBx5Yt8HqVPK2rjGQ+rVkJ4QvL1N3sNvCyJR9ZXjKlNXqH5YJb0F7xVgG3KZD9H3Zw==',
    upper(replace(gen_random_uuid()::text, '-', '')),
    gen_random_uuid()::text,
    false,
    false,
    true,
    0,
    'Campaign',
    'Admin',
    'Admin',
    true,
    CURRENT_TIMESTAMP,
    true,  -- Force password change on first login
    NULL
);

-- Verify the accounts were created
SELECT "Email", "FirstName", "LastName", "Role", "ForcePasswordChange" 
FROM "AspNetUsers" 
WHERE "Email" IN ('superadmin@campaign.com', 'admin@campaign.com');