name: t4h-canvas
region: nyc
services:
- name: api
  image:
    registry_type: DOCR
    repository: t4h-canvas-api
    tag: latest
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  health_check:
    http_path: /health
    timeout_seconds: 10
  envs:
  - key: ASPNETCORE_ENVIRONMENT
    scope: RUN_TIME
    value: Production
  - key: ASPNETCORE_URLS
    scope: RUN_TIME
    value: http://+:8080
  - key: ConnectionStrings__DefaultConnection
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: JWT_SECRET
    scope: RUN_TIME
    type: SECRET
    value: "CHANGE_THIS_TO_A_SECURE_32_CHAR_STRING"
  - key: JwtSettings__Secret
    scope: RUN_TIME
    value: ${JWT_SECRET}
  - key: JwtSettings__Issuer
    scope: RUN_TIME
    value: https://t4h-canvas.ondigitalocean.app
  - key: JwtSettings__Audience
    scope: RUN_TIME
    value: https://t4h-canvas.ondigitalocean.app
  - key: JwtSettings__ExpirationMinutes
    scope: RUN_TIME
    value: "480"

static_sites:
- name: frontend
  source_dir: /frontend
  git:
    repo_clone_url: https://github.com/maqboolp/CanvassingApp.git
    branch: main
  build_command: npm ci && npm run build
  output_dir: build
  routes:
  - path: /
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: https://t4h-canvas.ondigitalocean.app

databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "15"