name: t4h-canvas
region: nyc
services:
- name: api
  dockerfile_path: deployment/Dockerfile
  source_dir: /
  github:
    repo: maqboolp/CanvassingApp
    branch: main
    deploy_on_push: true
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  health_check:
    http_path: /health
  envs:
  - key: ASPNETCORE_ENVIRONMENT
    scope: RUN_TIME
    value: Production
  - key: ASPNETCORE_URLS
    scope: RUN_TIME
    value: http://+:8080
  - key: ConnectionStrings__DefaultConnection
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: JwtSettings__Secret
    scope: RUN_TIME
    value: ${JWT_SECRET}
  - key: JwtSettings__Issuer
    scope: RUN_TIME
    value: https://t4h-canvas.ondigitalocean.app
  - key: JwtSettings__Audience
    scope: RUN_TIME
    value: https://t4h-canvas.ondigitalocean.app
  - key: JwtSettings__ExpirationMinutes
    scope: RUN_TIME
    value: "480"

static_sites:
- name: frontend
  dockerfile_path: deployment/Dockerfile.frontend
  source_dir: /frontend
  github:
    repo: maqboolp/CanvassingApp
    branch: main
    deploy_on_push: true
  build_command: npm run build
  output_dir: build
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
  routes:
  - path: /
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: https://t4h-canvas.ondigitalocean.app

databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "15"